spring.application.name=Luftborn_Backend

spring.flyway.locations=classpath:db/migration,classpath:db/seed

springdoc.swagger-ui.tags-sorter=alpha

#Postgres Config
spring.datasource.url=${PG_URL}
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASSWORD}

#JPA Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Redis Config
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

#Jwt Config
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}
security.jwt.issuer=${JWT_ISSUER}

#Refresh Token
security.jwt.refresh-token.expiration-ms=${JWT_REFRESH_EXPIRATION_MS:2592000000}
security.jwt.cookie-name=refreshToken
security.jwt.cookie-secure=false
